-- AlterTable
ALTER TABLE "token" ADD COLUMN     "date_Created" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "date_ended" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "used_receipts" ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
